### ISSUE TITLE
Certificate extension not found error

### ISSUE THREAD

**Issue by tfheen** [rhboot/pesign#19]
I'm trying to get pesign to sign using a key and cert I have on a yubikey, but it errors complaining about "Certificate extension not found":

```
$ /tmp/zz/pesign/src/pesign --certdir=$PWD -t "PIV_II (PIV Card Holder pin)" -c "/CN=Debian Test Secure Boot Signer" --sign -i /boot/efi/EFI/debian/grubx64.efi -o signed.efi
Enter Password or Pin for "PIV_II (PIV Card Holder pin)":
cms_common.c:find_certificate:470: could not find certificate in list: Certificate extension not found.
pesign: Could not find certificate /CN=Debian Test Secure Boot Signer
```

I followed the recipe from https://fedoraproject.org/wiki/User:Pjones/SecureBootSmartCardDeployment on how to generate the certs, and https://dennis.silvrback.com/openssl-ca-with-yubikey-neo for loading it onto the smart card.

What certificate extension is it looking for?

**Comment by bluca** [comment]
Hi @tfheen - I've read on the Debian mailing list that you eventually managed to get this working, do you have a howto or a list of steps written somewhere public? I'm going through the same process and would be nice to avoid reinventing the wheel :-)
Thanks!

**Comment by tfheen** [comment]
@bluca, I ended up with `pesign --certdir=$PWD -t "PIV_II (PIV Card Holder pin)" -c "Certificate for Digital Signature" --sign -i /tmp/bootx64.efi -o /tmp/bootx64.signed.efi` (adjust paths as appropriate). Does that work for you?

**Comment by bluca** [comment]
I'm having troubles, as pesign keeps asking for a password/passphrase.
This happens regardless of whether both the DB and the x509 private keys were created with a password/passphrase or not:

```
$ rm tmp; pesign --certdir=$PWD -t "PIV_II (PIV Card Holder pin)" -c "Certificate for Digital Signature" --sign -i test -o test_sign
Enter Password or Pin for "PIV_II (PIV Card Holder pin)":
Enter passphrase for private key: 
Enter passphrase for private key: 
Enter passphrase for private key:
```

Signing other things bypassing pesign, like a kernel module using pkcs11:... tokens, works just fine.

Any idea?

This is on Debian Stretch btw.

**Comment by frozencemetery** [comment]
Hi @bluca, are you still seeing this?

**Comment by bluca** [comment]
I have long moved on from this topic, sorry

**Comment by frozencemetery** [comment]
No worries, thanks for the reply.
