### ISSUE TITLE
pesign daemon treats stdin as a tty and crashes

### ISSUE THREAD

**Issue by jcristau** [rhboot/pesign#22]
Hi,

I'm trying to setup pesign with a yubikey.  When using standalone pesign, interactively, things seem to work, but I want a noninteractive signing process, so was looking at the daemon/client stuff.  Unfortunately, even after running pesign-client --unlock, pesign-client --sign causes the daemon side to die because sign_blob sets the password func to readpw, which assumes that stdin is a tty.  Then calculate_signature_space calls exit(1) which kills the daemon.

It seems like in daemon mode, the pin passed to pesign-client --unlock should maybe be reused for signing?  Or maybe --sign should accept the --pinfile/--pinfd options and use them?

**Comment by frozencemetery** [comment]
We use the daemon noninteractively today, so presumably this has been fixed.
