### ISSUE TITLE
pesign fails to build with standard Fedora flags

### ISSUE THREAD

**Issue by r4f4** [rhboot/pesign#42]
pe_updatefile.c: In function '__pe_updatemmap':
pe_updatefile.c:135:3: error: #warning this is not done yet. [-Werror=cpp]
  #warning this is not done yet.
   ^~~~~~~
cc1: all warnings being treated as errors

**Comment by r4f4** [comment]
The problem is not the Fedora flags, but `Make.defaults` is including `-Werror` to `CFLAGS`.

**Comment by vathpela** [comment]
Should be fixed by https://github.com/rhboot/pesign/commit/3698a5c5d46d89b9ed9c6fd84e63e47c74d4a776 , but I typoed the issue number in the commit.
