### ISSUE TITLE
Can't build with LLVM/clang

### ISSUE THREAD

**Issue by tpgxyz** [rhboot/pesign#47]
I'm building pesing-0.112 with LLVM/clang-7.x

Here is the first issue

```
+ /usr/bin/make -O -j32 PREFIX=/usr LIBDIR=/usr/lib64
make[1]: Nothing to be done for 'deps'.
/usr/bin/make -f /builddir/build/BUILD/pesign-0.112/Make.deps deps SOURCES="pe_nextscn.c libdpe.c pe_rawfile.c pe_allocspace.c pe_opthdr.c pe_updatenull.c pe_error.c pe_updatefile.c pe_getscn.c pe_getdatadir.c pe_getshdr.c pe_readall.c pe_addcert.c pe_end.c pe_begin.c pe_getpehdr.c pe_update.c"
make[2]: Entering directory '/builddir/build/BUILD/pesign-0.112/libdpe'
/usr/bin/clang -Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4  -fPIC -flto -Qunused-arguments  -Wall -Werror -Wno-cpp  -Wsign-compare -Wno-unused-result -Wno-unused-function -std=gnu11 -fshort-wchar -fPIC -flto -fno-strict-aliasing -fno-merge-constants -fkeep-inline-functions -D_GNU_SOURCE -DCONFIG_x86_64 -I/builddir/build/BUILD/pesign-0.112/include      -Werror  -MM -MG -MF .pe_allocspace.d pe_allocspace.c
make[2]: Leaving directory '/builddir/build/BUILD/pesign-0.112/libdpe'
BUILDSTDERR: clang-7: error: optimization flag '-fno-merge-constants' is not supported [-Werror,-Wignored-optimization-argument]
BUILDSTDERR: clang-7: error: optimization flag '-fkeep-inline-functions' is not supported [-Werror,-Wignored-optimization-argument]
BUILDSTDERR: make[2]: *** [/builddir/build/BUILD/pesign-0.112/Make.deps:9: .pe_allocspace.d] Error 1
BUILDSTDERR: make[2]: *** Waiting for unfinished jobs....
```
Here is the second issue:
```
make[1]: Entering directory '/builddir/build/BUILD/pesign-0.112/libdpe'
/usr/bin/clang -Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4  -fPIC -flto -Qunused-arguments -Wno-error=ignored-optimization-argument  -Wall -Werror -Wno-cpp  -Wsign-compare -Wno-unused-result -Wno-unused-function -std=gnu11 -fshort-wchar -fPIC -flto -fno-strict-aliasing -fno-merge-constants -fkeep-inline-functions -D_GNU_SOURCE -DCONFIG_x86_64 -I/builddir/build/BUILD/pesign-0.112/include      -Werror  -c -o pe_opthdr.o pe_opthdr.c
make[1]: Leaving directory '/builddir/build/BUILD/pesign-0.112/libdpe'
BUILDSTDERR: clang-7: warning: optimization flag '-fno-merge-constants' is not supported [-Wignored-optimization-argument]
BUILDSTDERR: clang-7: warning: optimization flag '-fkeep-inline-functions' is not supported [-Wignored-optimization-argument]
BUILDSTDERR: pe_allocspace.c:64:33: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
BUILDSTDERR:         struct section_header shdr = { 0, }, tmp_shdr;
BUILDSTDERR:                                        ^
BUILDSTDERR:                                        {}
BUILDSTDERR: 1 error generated.
BUILDSTDERR: make[1]: *** [/builddir/build/BUILD/pesign-0.112/Make.rules:33: pe_allocspace.o] Error 1
BUILDSTDERR: make[1]: *** Waiting for unfinished jobs...
```
Here you can find sources:
https://github.com/OpenMandrivaAssociation/pesign

**Comment by jandryuk** [comment]
Hi,

https://github.com/rhboot/pesign/commit/377da9b127b89a30ef2258bc3bfaee6565484611 causes a build failure in OpenXT/OpenEmbedded/Yocto
> 
> x86_64-oe-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse recipe-sysroot-ar  libdpe.a libdpe.o pe_addcert.o pe_allocspace.o pe_begin.o pe_end.o pe_error.o pe_getdatadir.o pe_getpehdr.o pe_getscn.o pe_getshdr.o pe_nextscn.o pe_opthdr.o pe_rawfile.o pe_readall.o pe_update.o pe_updatefile.o pe_updatenull.o
> x86_64-oe-linux-gcc: error: recipe-sysroot-ar: No such file or directory
> x86_64-oe-linux-gcc: error: libdpe.a: No such file or directory

OE sets:
`CC=x86_64-oe-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/home/build/openxt-sm-master/build/tmp-glibc/work/core2-64-oe-linux/pesign/gitAUTOINC+377da9b127-r0/recipe-sysroot`

This breaks settings AR:
`AR	:= $(CROSS_COMPILE)$(if $(filter $(CC),clang),llvm-ar,$(notdir $(CC))-ar)`
since it becomes `x86_64-oe-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/home/build/openxt-sm-master/build/tmp-glibc/work/core2-64-oe-linux/pesign/gitAUTOINC+377da9b127-r0/recipe-sysroot-ar`

OE sets AR, so `AR ?= ` will work, but then ARFLAGS is not setup properly.  I'm not sure how to handle that.

**Comment by jandryuk** [comment]
Okay, so the OE provided AR doesn't quite work since it's `x86_64-oe-linux-ar`.  The linking fails with undefined references, and `ar` prints messages about needing a plugin for LTO.  Turns out you need `gcc-ar` (`x86_64-oe-linux-gcc-ar`) to automatically handle LTO.  Same for ranlib.

**Comment by vathpela** [comment]
I think https://github.com/rhboot/pesign/commit/6205d306fd3b58e94c2a6ad0af2566a42d1a249c may fix this for you, and if not https://github.com/rhboot/pesign/commit/192b74712e3ad7fcc0189cbc6eb44389825a8106 should make some stuff that's still weird easier to work around.

**Comment by vathpela** [comment]
... you probably also need e410dcda44b177a7171c476faf6d736895ed5674 for all the cases you're *not* manually setting CCLD.

**Comment by jandryuk** [comment]
Thanks!  I was able build master.  Looks like CC is not detected as gcc, so it no longer tries LTO.  The regular x86_64-oe-linux-ar can then link.

Thanks, again!

**Comment by vathpela** [comment]
I can build locally with clang as well, so I'm going to go ahead and close this issue out.
